location_name      = "South India"
resourcegroup_name = "UAT-RG"
network_name       = "uat-vnet"
# subnet_name          = "uat_private_subnet"
bastion_subnet_name  = "bastion_server_subnet"
bastion_subnet_range = ["192.0.2.0/24"]
web_subnet_name      = "webserver_subnet"
web_subnet_range     = ["192.0.5.0/24"]
app_subnet_range     = ["192.0.1.0/24"]
app_subnet_name      = "appserver_subnet"
dbsubnet_range       = ["192.0.4.0/24"]
dbsubnet_name        = "database_subnet"
nat_name             = "nat_gateway_uat"
nat_public_ip_name   = "nat_uat_public_ip"

vm_machine_name         = "web-server-uat"
ubuntu_vm_publicIp_name = "bastion_server_public_ip"
bastion_interface_name  = "bastion_network_interface"
web_interface_name      = "web_network_interface"
app_interface_name      = "app_network_interface"
db_interface_name       = "db_network_interface"